### ISSUE TITLE
Automate Issue#2954

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#695] opened 2017-06-29 15:58 UTC
<del>https://pulp.plan.io/issues/2847</del>
<del>https://pulp.plan.io/issues/2861</del>
<ins>https://pulp.plan.io/issues/2954</ins>

**Comment by preethit** [comment] 2017-06-29 18:21
This may be an opportunity to learn about pulp-fixtures for @kersommoura and @kdelee

**Comment by Ichimonji10** [comment] 2017-06-30 20:23
I think the wrong Pulp issue was linked to. I've corrected the link.

The issue is modestly hard to automate. @kersommoura and @kdelee can probably automate it. I may also knock it out. I've talked to the devs about this issue, and automating it is a pretty high priority.

**Comment by Ichimonji10** [comment] 2017-06-30 20:26
This issue is part of a trio including:

* #695 (part A)
* #694 (part B)
* #701 (part C)

**Comment by kersommoura** [comment] 2017-07-20 17:43
@kdelee I will work on this one

**Comment by daviddavis** [comment] 2017-08-04 19:50
FYI, I've closed out #2861 as WONTFIX as it pertains to celery 3 and opened a new task for celery 4:

https://pulp.plan.io/issues/2954

I recommend either re-using this smash test issue for #2954 or creating a new smash test issue for #2954.

**Comment by preethit** [comment] 2017-08-07 15:12
As per the above comment adding 
https://pulp.plan.io/issues/2954

**Closed** 2019-10-31 18:47 UTC
Labels: Issue Type: Test Case, pulp 2 - closed - wontfix
