### ISSUE TITLE
Add new test for "Reading an RPM repo returns incorrect rpm_unit_counts"

### ISSUE THREAD

**Issue by omaciel** [PulpQE/pulp-smash#82] opened 2016-02-03 19:33 UTC
Please read the original [issue](https://pulp.plan.io/issues/1570) which describes a regression found on Pulp 2.8.0 Beta, and automate it.

**Comment by Ichimonji10** [comment] 2016-02-03 19:38
I think we have a test for this. /me checks

**Comment by omaciel** [comment] 2016-02-03 19:39
@Ichimonji10 cool! That would be awesome!

**Comment by Ichimonji10** [comment] 2016-02-03 19:40
[This test](http://pulp-smash.readthedocs.org/en/latest/api/pulp_smash.tests.rpm.api_v2.test_sync_publish.html#pulp_smash.tests.rpm.api_v2.test_sync_publish.SyncValidFeedTestCase.test_unit_count_on_repo) targets that issue. The relevant test code looks like this:

```python
        counts = self.repo.get('content_unit_counts', {})
        for unit_type, count in {
                'rpm': 32,
                'erratum': 4,
                'package_group': 2,
                'package_category': 1,
        }.items():
            if (unit_type == 'rpm' and self.cfg.version >= Version('2.8') and
                    selectors.bug_is_untestable(1570)):
                continue
            with self.subTest(unit_type=unit_type):
                self.assertEqual(counts.get(unit_type), count)
```

**Comment by omaciel** [comment] 2016-02-03 20:13
@Ichimonji10 shouldn't `SyncValidFeedTestCase` be decorated with a skip flag until the redmine issue is resolved?

**Comment by Ichimonji10** [comment] 2016-02-03 22:01
@omaciel Nope.

* The test method shown above functions correctly on Pulp 2.7.
* Only RPM unit counts are incorrect. We still want to assert that Pulp 2.8 correctly reports `erratum`, `package_group` and `package_category` unit counts. The test method shown above does that.
* The other test methods in `SyncValidFeedTestCase` should still run.

**Comment by Ichimonji10** [comment] 2016-02-04 00:06
Cell phones are convenient for consumption, but not authorship. @omaciel, I've edited the explanation above for (hopefully) improved clarity.

**Comment by omaciel** [comment] 2016-02-04 00:16
@Ichimonji10 hehe got it :) so I guess we can close this issue?

**Comment by Ichimonji10** [comment] 2016-02-04 00:18
I think so, yes. As soon as the relevant pulp.plan.io issue is moved to the MODIFIED state, the appropriate test will start running again. If we hear nothing, then that means the issue is fixed. And if we see a new test failure, we know that the fix didn't work. Easy as that. :smile:

**Comment by Ichimonji10** [comment] 2016-02-04 00:19
I'll let you keep this open or close it, though.

**Comment by Ichimonji10** [comment] 2016-02-05 17:32
As per an IRC discussion, I'm closing this issue. A test is in place for [Pulp issue #1570](https://pulp.plan.io/issues/1570). It is currently being skipped, but will start running again when the Pulp issue is moved to the MODIFIED state.

**Closed** 2016-02-05 17:32 UTC
Labels: high priority
