### ISSUE TITLE
Automate https://pulp.plan.io/issues/2874

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#715] opened 2017-07-17 19:16 UTC
Automate https://pulp.plan.io/issues/2874

**Comment by preethit** [comment] 2017-11-20 15:07
This is high on sat list. Prioritizing for automation.  I am adding a Label High for the ones we should prioritize.

**Comment by kersommoura** [comment] 2017-12-06 16:41
@preethit @Ichimonji10, I tried to re-create the race condition scenario.

According to the issue, and asking around the race condition should appear when  **calculate applicability for consumers with the same profile in parallel**.

To achieve this I follow these steps:

1. Create, sync and publish a repo.
2. Create x number of consumers, and bind them to the previous repo.
3. Create the same consumer profile for all the users.
4. Use Threads to simulate parallelism, and request to generate applicability for all users in parallel.

With step 4 I was expecting to re-create the race condition. I tried different number of consumers, and Threads. None of them re-produce the race condition described in the issue.

Not sure, if we will be able to re-create this issue.

**Comment by kersommoura** [comment] 2017-12-06 16:44
Few useful definitions about this topic:

* Consumer: machine registered with Pulp. This machine has some Pulp repositories enabled in its YUM config.

* Consumer Profile: Set of packages installed on consumer machine.
* Applicability: Which packages and/or errata should be upgrade or applied. Applicability is calculate for each consumer profile.

**Comment by rplevka** [comment] 2017-12-13 14:33
@kersommoura 
- i think the consumer profile also contains the info about the enabled repos.

- i was testing this RC downstream. I did a dirty trick of tweaking the pulp code by injecting an artificial `sleep(x)` inside the branch for not existing profile && just before the command to create it. - this gave me enough time to upload a package profile for another consumer, which led it to end in the same branch (applicability profile not ready yet), put on sunglasses and grab some popcorn.

after 30 seconds elapsed, i was a witness of a colossal `DuplicateKeyError`.
![abomb](https://media1.tenor.com/images/b76d95d52dfa6c3b316c0b486d3ef3e0/tenor.gif)

i don't think you have much chances hitting this reliably without messing with the code.
Anyway, note, that since the applicability profile gets created once, it will stay there and all other users sharing the same profile will use it (you might need to remove it from db)

**Comment by preethit** [comment] 2017-12-14 16:21
@kersom, @Ichimonji10 is it worth adding a test with the steps you mentioned even though you were not able to recreate the race condition?

**Comment by kersommoura** [comment] 2017-12-14 16:23
@preethit , I am doing few extras tests, and I will inform you.

**Comment by kersommoura** [comment] 2018-01-15 14:15
After further investigation, and many different attempts to recreate this race condition.
Since we could not recreate the race condition in a reproducible way. And the aforementioned discussed steps to recreate the issue require mess with pulp internals.
I am closing this issue, as not suitable for automation.  If there is any other understanding, feel free to re-open this issue.

**Closed by kersommoura** 2018-01-15 14:15 UTC
Labels: High, Issue Type: Test Case
