### ISSUE TITLE
Add new test for "Uploading the same Content Unit twice"

### ISSUE THREAD

**Issue by omaciel** [PulpQE/pulp-smash#81] opened 2016-02-03 18:54 UTC
As per this [issue](https://pulp.plan.io/issues/1406), there is a new regression in Pulp 2.8 Beta when one tries to upload the same content (ie. rpms, puppet modules, etc) to an existing repository. We need a new automated test that does the following:

* Create a new feed-less repository
* Manually import a valid content type (i.e. RPM, etc)
  * Assert that the content type was successfully uploaded into the repository
* Manually try to import the same exact content type to the same repository
  * Assert that a PulpCodedException is raised

We should make sure that all valid content types (rpms, puppet modules, docker images, etc) are used for this test to make sure that we get the same, expected behavior across the board.

* [ ] docker v1
* [x] puppet
* [x] python
* [x] rpm

<ins>Not testable: docker v2 and ostree. See: <a href="https://github.com/PulpQE/pulp-smash/issues/81#issuecomment-214412605">here</a>.</ins>

**Comment by omaciel** [comment] 2016-02-03 19:18
@peterlacko please consider this issue your top priority :)

**Comment by peterlacko** [comment] 2016-02-04 17:56
Sure, will do!

**Comment by Ichimonji10** [comment] 2016-02-11 00:11
I'm self-assigning this.

* #90 needs more work vis–à–vis #103, and #61 is still open.
* I want to close the "high priority" issues.
* I have an idea for how to use mixins to refactor redundant code out of the various packages, and taking on this issue will allow me to explore that idea.

**Comment by Ichimonji10** [comment] 2016-02-11 22:16
Branch https://github.com/PulpQE/pulp-smash/compare/master...Ichimonji10:duplicate contains a first draft of tests for this issue. They all succeed at the moment, and they're structured so that common code can be re-used between the different plugins.

@bmbouter, this set of tests targets [Pulp #1406](https://pulp.plan.io/issues/1406). In that issue, @mhrivnak suggests that a `PulpCodedException` should be raised. Is this exception visible to an end user? Or is that an internal implementation detail?

As things stand, the test case asserts that it is possible to upload the same content to a single repository twice in a row, and that no errors are reported. From my understanding of the issue, this is how Pulp 2.7 and 2.8 should both act. Am I missing something here?

**Comment by bmbouter** [comment] 2016-02-12 19:55
@Ichimonji10 Any `PulpCodedException` is designed to be user-facing. When we raise them, the Pulp httpd middleware should convert them to JSON and hand them back to the user in a structured way. If we're generically raising a 500 without any coded exception, I consider that a bug.

Regarding [Pulp #1406](https://pulp.plan.io/issues/1406), in 2.7 I expect no exception to be raised since 1406 was introduced in 2.8.0. I expect 2.8.0+ to not have an exception raised when issue 1406 is at MODIFIED.

If there are more questions let me know please post back. Thanks @Ichimonji10

**Comment by Ichimonji10** [comment] 2016-02-12 20:23
Let me make sure I have this right. In a nutshell, when duplicate content units are uploaded:

* No exception should be raised in Pulp 2.x.
* An exception should be raise in Pulp 3.x.

**Comment by bmbouter** [comment] 2016-02-12 20:30
@Ichimonji10  We haven't defined a behavior for Pulp 3.x

Let me put it this way. In all Pulp 2.x versions no exception should be raised when uploading a unit that is already known to Pulp. In 2.7 and (likely) all versions prior this has not been a problem. On 2.8.0 there is a regressions which is what [Pulp 1406](https://pulp.plan.io/issues/1406) is tracking specifically. Once 1406 is resolved 2.8.0 will not raise an error either which will make it consistent with earlier versions. Does that make sense? Post back questions!

**Comment by Ichimonji10** [comment] 2016-02-12 20:35
Yes, that makes sense. Thank you.

**Comment by omaciel** [comment] 2016-02-23 23:07
Hi @PulpQE/quality-engineers where do we stand on this issue?

**Comment by preethit** [comment] 2016-02-24 12:52
@omaciel The issue is still being worked on as a blocker for 2.8. Its in an assigned state.
https://pulp.plan.io/issues/1406

**Comment by Ichimonji10** [comment] 2016-02-24 20:39
As of #121, Pulp Smash tests duplicate uploads for the docker plugin. The other plugins are untested.

**Comment by asmacdo** [comment] 2016-03-07 16:33
Completion of this issue should include either a port of the relevant pulp-automation tests or the creation of a separate issue:
https://github.com/RedHatQE/pulp-automation/blob/master/tests/general_tests/test_21_upload_cud.py

**Comment by Ichimonji10** [comment] 2016-04-25 15:52
One can upload Docker v2 content to a Pulp repository, and as soon as we find a place to host a docker image tarball, we can implement that test. See: http://pulp-docker.readthedocs.org/en/latest/user-guide/recipes.html#upload-v1-images-to-pulp

One cannot upload Docker v2 content directly into a Pulp repository. See: http://pulp-docker.readthedocs.org/en/latest/user-guide/concepts.html#upload

There doesn't appear to be any mechanism for uploading OSTree content to a Pulp repository. See:

* http://pulp-ostree.readthedocs.org/en/latest/search.html?q=upload&check_keywords=yes&area=default
* https://github.com/pulp/pulp/search?utf8=%E2%9C%93&q=ostree+upload

I'm updating the comment at the top of this thread appropriately.

**Comment by elyezer** [comment] 2016-04-27 12:34
Would be fedora people a good place to host the image tarball?

**Comment by Ichimonji10** [comment] 2016-04-27 14:18
I'd love it if we could do that. We're already hosting static RPMs there. Why not static tarballs too?

By the way, this seems highly related to #221. The process for generating the Docker tarball is:

```sh
docker pull busybox:latest
docker save busybox:latest > busybox:latest.tar
```

It's simple, but having those steps saved would be *great* from a reproducibility standpoint.

Maybe we should push these tools into a `pulp-smash-fixtures` repository? Both #221 and a docker script would bring in additional dependencies beyond what's listed in [Pulp Smash → About → Scope and Limitations → Portability](http://pulp-smash.readthedocs.org/en/latest/about.html#portability), and placing the scripts in a separate repository makes it clear that these scripts have their own set of dependencies. It's kinda like how we require Pulp systems but don't put tools for spinning up Pulp systems into Pulp Smash. Also, it'd let the binary blobs brought in by the RPM generation script stay separate.

**Comment by Ichimonji10** [comment] 2016-04-28 19:57
I've created a new repository, [Pulp Fixtures](https://github.com/PulpQE/pulp-fixtures). That repository has a make target for creating Docker fixtures, `make docker`. I make use of the fixture in my Docker duplicate upload tests, which can be found in my https://github.com/PulpQE/pulp-smash/compare/master...Ichimonji10:dup-up branch.

As soon as we can host the output of `make docker` somewhere, I'll be able to get that test updated accordingly and merged.

**Comment by elyezer** [comment] 2016-04-28 20:33
I will try to create a job that uploads the docker and RPM bits to fedorapeople.

**Comment by Ichimonji10** [comment] 2016-04-28 20:48
:+1: Thank you.

**Closed** 2016-05-04 21:16 UTC
Labels: high priority, test case
