### ISSUE TITLE
Test DocumentTooLarge error during merge of errata pkglists

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#553] opened 2017-02-10 18:58 UTC
https://pulp.plan.io/issues/2568

The issue may not have a clear reproducing steps
one scenario that we can cover is adding and epel7 repo to be synced during upgrade.

**Comment by goosemania** [comment] 2017-02-10 21:48
@preethit , give me some time, I will write here the exact scenario and I will probably create new updateinfo fixture repo to test it. Sorry for not doing it right away.

**Comment by goosemania** [comment] 2017-02-13 22:51
It was a tricky issue to find and it is not easy to reproduce as well, the following is a suggestion for the test scenario which unfortunately looks quite complicated.
I also have some mongodb dumps (they are in related BZ actually) which can help to create a system affected by the issue. Let me know if it is an option for you and if I can help there.

The main goal is to see that after applying the fix the migration worked correctly (aka all the necessary errata pkglists are still in place and correct, all the needless ones are cleaned up).

Steps to reproduce the issue (I added some description of the purpose of each step. Feel free to skip it if you do not want to dig into such details):

1. Create and sync repo A with pulp 2.8.4 or older, use fixtures/rpm-pkglists-updateinfo repo. 
_This step ensures that the old structure of pkglist is in db._

2. Upgrade to 2.8.5 <= pulp < 2.12.1.
_At this point we start to merge pkglists and extend their structure._

3. Change feed for repo A to fixtures/rpm-unsigned and sync.
_This step leaves old erratum pkglist structure for the repo A in place and adds a new one because pkglist is different._

4. Create and sync repo B 3 times (using force_full flag), use fixtures/rpm-pkglists-updateinfo. 
_This step just adds multiple records for some other repo with different pkglist for the same erratum._

5. Change feed for repo A to fixtures/rpm-updated-pkglist-updateinfo (I should create this one) and sync (using force_full flag) until DocumentTooLarge error occurs. 
_This step ensures that there were at least two changes for erratum pkglist._

What to verify after upgrade to pulp 2.12.1+:
 - you can do a force_full sync for repoA N+1 times and see no error where N is a number of syncs until you hit DocumentTooLarge error in a reproducer.
 - after publish of repo A you should find all the packages from the latest update of erratum in its pkglist (I will add details here if we give this scenario a go :))
 - the same ^ for repo B

Please, let me know if you'd like to do it the way I suggested, if you have any other ideas/simplifications, if you'd like to use db dumps. Based on the feedback I will add more details.

**Comment by elyezer** [comment] 2017-02-14 18:08
In order to install the 2.8.4 this URL [1] can be used. That is a temporary repo which will be removed when this issue is verified.

[1] https://repos.fedorapeople.org/repos/pulp/pulp/delme-if-rm2568-verified/

**Comment by goosemania** [comment] 2017-02-15 15:24
Here is a suggestion for the db approach.
### To check that issue no longer exists
 1. create and sync repo A, use any feed where errata exist, e.g. `fixtures/rpm-unsigned`
 1. make one of errata look the old, pulp 2.8.4, way (aka without `_pulp_repo_id`) and modify pkglist so it differs form the upstream one. Mongo commad to remove `_pulp_repo_id` and one package from pkglist: 
```
> db.units_erratum.update({"errata_id": "RHEA-2012:0055"},
                          {"$unset": {"pkglist.0._pulp_repo_id": ""},
                           "$pull": {"pkglist.0.packages": {"name": "walrus"}}})
```
 3. force sync of repo A, 2 times
 1. create and sync repo B using the same feed as for repo A
 1. create repo C and copy all the errata from repo B
 1. assert that in db in erratum pkglist:
 * there is still a collection without `_pulp_repo_id`
 * there is only one collection with `_pulp_repo_id == repo A`
 * there is one collection with `_pulp_repo_id == repo B`
 * there is no collection with `_pulp_repo_id == repo C`

### To check migration
 1. simulate the broken state for errata:
 * create and sync repo A, use any feed where errata exist, e.g. `fixtures/rpm-unsigned`
 * make multiple copies of collections in erratum
 ```
    > var sample_collection = db.units_erratum.find({"errata_id": "RHEA-2012:0055"})[0].pkglist[0]
    > for (i = 0; i < 10; i++) {
          db.units_erratum.update({"errata_id": "RHEA-2012:0055"},
                                  {"$push": {"pkglist": sample_collection}})
      }
 ```
 * modify collections to imitate an issue:
 -- collection with no `_pulp_repo_id`,
 -- multiple collections with the same name and same pkglits,
 -- last collection with the same name and different pkglist,
 -- at least one collection with different `__pulp_repo_id`.
```
    > var some_package = {"src": "http://smth.org", "name": "test", "sum": null, 
                          "filename": "test-1-1.noarch.rpm", "epoch": null,
                          "version": "1", "release": "1", "arch": "noarch"}
    > db.units_erratum.update({"errata_id": "RHEA-2012:0055"},
                              {"$unset": {"pkglist.0._pulp_repo_id": ""},
                               "$pull": {"pkglist.0.packages": {"name": "walrus"}},
                               "$set": {"pkglist.3._pulp_repo_id": "different_repo_id"},
                               "$push": {"pkglist.10.packages": some_package} })
```

 2. after running migration assert that in db:
 * there are 3 collections in pkglist
 * there is still pkglist without `_pulp_repo_id`
 * there is only one and the newest (includes `some_package` in my example) pkglist
 for `_pulp_repo_id == repo A`
 * there is a pkglist for `_pulp_repo_id == "different_repo_id"`


It is also worth checking that migration does not change/break anything in the normal non-broken state:
 * a case when there is only one collection in pkglist
 -- create and sync repo with some feed
 -- run migration
 -- assert that nothing changed in pkglist
 * a case when there are multiple collections in pkglist
-- create and sync 2 repos with the same feed (do not use copy)
-- run migration
-- assert that nothing changed in pkglist

**Comment by preethit** [comment] 2017-03-10 18:25
This may be better to manually test with upgrade testing.

**Comment by Ichimonji10** [comment] 2017-07-03 20:51
The steps for reproducing this are a bit intense. I'm especially wary of running mongod commands. Does anyone object to us closing this issue and manually testing it as needed?

**Comment by goosemania** [comment] 2017-07-04 09:30
@Ichimonji10 , FWIW, no objections from my side. This change was released a while ago and no issues so far + it has already been tested manually (by downstream).

**Closed** 2017-07-05 14:01 UTC
Labels: Issue Type: Test Case
