### ISSUE TITLE
As an un-authenticated user I can 

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#749] opened 2017-08-14 14:38 UTC
[MVP Authentication](https://pulp.plan.io/projects/pulp/wiki/Pulp_3_Minimum_Viable_Product#Authentication)

~~-  Obtain a JWT token by using a username and password.~~

**At the time of creating this issue, these taxed items were not confirmed in the MVP document.**

**Comment by asmacdo** [comment] 2017-09-27 23:16
@kersommoura, I'm closing because it appears to be a dupe of #751, please reopen if you had another intention for this issue.

**Closed by asmacdo** 2017-09-27 23:16 UTC
Labels: Issue Type: Test Case, Pulp Version: 3

**Comment by kersommoura** [comment] 2017-09-27 23:25
@asmacdo, thanks.
