### ISSUE TITLE
Lazy download repo content task fails silently

### ISSUE THREAD

**Issue by elyezer** [PulpQE/pulp-smash#523] opened 2017-01-30 15:35 UTC
Waiting for reproduce steps.

For more information see: https://pulp.plan.io/issues/2458

**Comment by kersommoura** [comment] 2017-10-06 15:25
As stated in the https://pulp.plan.io/issues/2458

>     1. Creating a repository with a on_demand download policy.
>     2. Synchronize the repository.
>     3. Using mongo, update one of the URLs in the catalog entries for that importer to be incorrect.
>     4. As described in the description, kick off the repository download task.

Based on that, I suggest to close this issue. Since the only way to recreate the issue is using Pulp internals, mongo as described on the step3.

@Ichimonji10, what do you think?

**Comment by Ichimonji10** [comment] 2017-10-09 17:32
I agree.

**Closed by Ichimonji10** 2017-10-09 17:32 UTC
Labels: Issue Type: Test Case
